# Algorithm
sentiment_ini:
- [0.7, 0.3]
- [0.8, 0.2]
- [0.9, 0.1]
support: 0.5
doji: 0.4
sentiment_mult: 1.5
pred_mult: 1
prediction: 0.8
swap: 0.05

# Strategy
max_trans: 15
max_margin_risk: 0.65
stop_limit: 0.1
max_records: 60
